services:
  db:
    image: postgres:18
    container_name: postgres_example
    restart: always
    environment:
      POSTGRES_USER: postuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dbplayer
    ports:
      - "5434:5432"
